include $(SOURCE_BASE)/base/make/cflags

TYPE = lib
MODULE = tdcpfh

CFLAGS_ADD = -I$(SOURCE_BASE)/base/ds/include
LIBS = -lofcom -lpgmdd -ldsio -ltcfh

SOURCES = \
	tdcpfh_main.c \
	tdcpfh_version.c

include $(SOURCE_BASE)/base/make/rules

